language: ruby
rbenv:
- 2.5.3
addons:
  postgresql: 9.6
script:
- yarn
- RAILS_ENV=test bundle exec rake db:test:prepare --trace
- bundle exec rspec
deploy:
  provider: heroku
  app:
  run: rails db:migrate
  run: rake assets:precompile